apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-secret
type: Opaque
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:Xqy2yCKNc8NMdqxt/j9n0L59Ys93kBVGMXM2SM8KgpijVTe8PYFQPK8FHjFt+Fc1Uj1KsoiRmE/8wfZcq3kJVjqdu7ZCpilVPgZiw6r5TONGpVTmCJrOBsfQ/yE4V3KdERhSyuJmTV34lTVOc8ks6zKlI8lu9D/pQQ==,iv:b03LW/JzRhQI8eTohvQw5ATXDKJRuoAUmv39i2UoBcw=,tag:6C05A06aBvGRu5I9vDRRUg==,type:str]
sops:
    age:
        - recipient: age1e7w4zae6vaaw5csn6l94m2vmkrlapurjv3qrd8k675dm9p8rtp8q8fcyen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV2gzaGgzcDN6bE9zNHVD
            djM4VzM2dTc4Rll3QTBtcGI5ZlpDMWNJZkNVClRuTXloQjJnOHlxY1BkandvQ2RO
            NXBOZmJpVWJrTUt1RTlaVlp1SGlWZVkKLS0tIDFRL2dmN2dUMFNmWG5WclJRaUtO
            YU9xcEJGcXRkeEZwcmdLTGFIZnlzRkkKE0bn9IcpMa7cYH8LJjk5I0SvcvphwuyO
            XkwDOmMmFgBvD7pwWw2wzpxLkEMY7O8TgDL9TVhKk2Q9ux141uT0YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T19:37:48Z"
    mac: ENC[AES256_GCM,data:LKZ4Vp+ydsPnHKzgm96MyYPlGH02u+0Dqzt+zXE5W0Xq1+M1II8BcaMUzkMw3o4YkwzkYNhZzYxp2fwplx/NArG66HWZKqnNQd7I9csGecKtRDq9jL5AjYOPC4DKsfPvbOF7V/MzuLFWqKEsFoMJcjZM/WzAG6kguvwoLI/xvds=,iv:ZN2TJVTHecrROeQmwEYFy00uQ3lAFzTEiZCIsz23byc=,tag:n2inJC7w2K1dtvO+5b0D1g==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
