apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:D75wdaHRl2E=,iv:ALqZrv64YVan7S5UdrUIDWf/Fiqo3xnRAvRLxelDAME=,tag:fPy/S6GI5qoeh2ZHpvB8og==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fYypiZbi/zyepg5+,iv:AlxVO/J7Mzx4qrN4BssK/fMneS0e/vLBeThQQsIefEY=,tag:7sAnoljYzSkaRZTTaRlffQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:mzLOp7yT660=,iv:1MO1cgIb65ZrONnSTPqyLxH89EzXhHMTWfz8KxmnET0=,tag:kKfqIJXWAPhIe8/S+5WRdg==,type:str]
sops:
    age:
        - recipient: age1e7w4zae6vaaw5csn6l94m2vmkrlapurjv3qrd8k675dm9p8rtp8q8fcyen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaTdaTThvaEFoNW41Qkd5
            aW1IOTFKYU04SHFEQTBlUy9LVVRtUVMvSW40CmdacGQyT0tsV0Q5YU9GSkUza0dO
            MVhLYU54eWtEYU43Q01OaitlR2lEMW8KLS0tIHhvakE0MTh0RlAxT2hlZU9ycGxU
            K09JK3JtYVRtS1BRdk92dnFSNFRwTGMKsMLduoo616G9lAkPTgjFW0vfFxK45BOY
            zrbmnzte4i84Rp1GcsuOhIYxnwJ6i1InG2nwg0+74C72GpwlnPl8ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T19:35:50Z"
    mac: ENC[AES256_GCM,data:xgCResG9DBaD73ajDV3P45VZQQRkTUR/aTAClHksSiXX2shLkWculR5cwpZY39DdwtTiaC58/WORJv2xSsMixFSBhWObHwp0K2XpzPDVn+VhzMuC+twqfJcS4NagJFZG4EUV4YkTWyRwVXW060QJjLBXFrt+7l1qqBz7UOTn+II=,iv:1GYWlgrL+3KRPpdMBb7FuXGCu0hdco6eMo7LFmaXQdw=,tag:N5T/XwEIvUkfwt3mmeVcIA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
